# Generated by Django 4.0.5 on 2022-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='video/%y'),
        ),
    ]
